### ISSUE TITLE
Incorrect formula in readme

### ISSUE THREAD

**Issue by ceesem** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#19]
The readme describes the formula for the threshold in the section "Implications of the parameters of the threshold growth rate". However, that formula would equate the `alpha` and `aggressiveness` parameters. Looking at the code, it seems like the `aggressiveness` parameter needs to be an exponent, not a multiplication.

**Comment by Kramer84** [comment]
Thanks for having pointed out the mistake, it's corrected now.
