### ISSUE TITLE
Python 3.11 Wheels + Source Distribution

### ISSUE THREAD

**Issue by william-silversmith** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#20]
Hi again! Thanks for supporting this package!

Would it be possible to get py311 wheels on PyPI?

Thanks!
Will

**Comment by william-silversmith** [comment]
Also another idea: create a source distribution `python setup.py sdist` so that clients can compile on architectures that are not explicitly supported.

**Comment by bwoodsend** [comment]
Sure, shouldn't take long to increment some version numbers...

**Comment by bwoodsend** [comment]
> Also another idea: create a source distribution python setup.py sdist so that clients can compile on architectures that are not explicitly supported.

What architectures do you have in mind here? I've made a point of choosing the same ones that numpy uses so if we did provide an sdist so that people could build from source, the only cases where it would be used would also require building numpy from source too which is not a task taken on lightly.

**Comment by william-silversmith** [comment]
Not sure, I just always provide it as a fallback in case there's a situation I haven't anticipated or gotten to like e.g. py312 coming out.

**Comment by bwoodsend** [comment]
I've pushed a new release with 3.11 wheels.

In my experience, people with versions of pip that are too old to recognise wheel's platform tag for their platform tend to install from sdist by accident and end up reporting nonsense bugs about installing not working. Anyone who wants an sdist and knows that they'll need a compiler to build it can always use `pip install git+https://github.com/Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction`.
