### ISSUE TITLE
Python 3.12 Wheels

### ISSUE THREAD

**Issue by william-silversmith** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#22]
Hi!

Happy holidays! 🌟

I've been updating my libraries for Python 3.12 and just wanted to check in and see if it would be possible to get updated wheels uploaded to PyPI.

Thanks so much for all the work you've put into this. 

Will

**Comment by bwoodsend** [comment]
That's them up. Thanks for the reminder!

**Comment by william-silversmith** [comment]
Thank you so much! Have a happy new year!

**Comment by Kramer84** [comment]
I'll upload them on PyPI as soon as possible ! Happy new year :)

**Comment by bwoodsend** [comment]
@Kramer84 they're already there
