### ISSUE TITLE
Upgrade numpy from 1.26.4 to 2.0.1

### ISSUE THREAD

**Issue by FPerezHernandez92** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#23]
Thank you very much for your work. It is very useful. 

I have tried to update numpy to version 2.0.1. When doing so, pyfqmr gives the following error. 

` 
Python 3.11.9 (main, Aug  2 2024, 14:42:39) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfqmr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/pyfqmr/__init__.py", line 1, in <module>
    from .Simplify import *
  File "pyfqmr/Simplify.pyx", line 1, in init pyfqmr.Simplify
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
`

Are there any plans to release a new version of pyfqmr that will make it work?

**Comment by Kramer84** [comment]
Thanks you for opening the issue and your interest in the package. We will be trying to keep everything as much up to date as possible - mostly thanks to @bwoodsend and his fast inputs. I'll close this issue for now, as pull [#24](https://github.com/Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction/pull/24) seems to be an appropriate provisional solution.

**Comment by bwoodsend** [comment]
... and that's it released.
