### ISSUE TITLE
Put it on PyPI!

### ISSUE THREAD

**Issue by bwoodsend** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#3]
This is the fastest decimation package I've encountered so far. If this gets on PyPI, it'll make my life so much easier. I just want to see this finished to an extent that I can make this a dependency. i.e.

* Fixup the package metadata so that it has a proper name and version
* Build wheels on CI/CD
* Put it on PyPI

I've done wheels for C extensions before and I'm happy to do the heavy lifting here. I just want your OK before I start...

**Comment by Kramer84** [comment]
@bwoodsend  Thank you very much for your interest for this wrapper! I would be glad to see this project go on, as I had abandonned it for a while (I haven't even seen the notification for this issue). 

If you want to add features or adapt the code to put it on PyPI you can fork my repo and ask for a merge at any time, or I could add you as a contributor, which would make this even easier. Tell me what you prefer.

**Comment by bwoodsend** [comment]
OK, I'll start by firing off pull requests and you can maybe add me later. Give me a few says though...

**Comment by Kramer84** [comment]
Awesome! I have created the dev branch yesterday, and made some changes based on  [this repo](https://github.com/AshleySetter/HowToPackageCythonAndCppFuncs) which tries to explain python packaging with Cython. I did not yet managed to create a setup file that would allow the module to be built installed at the same time, so it is good to have your expertise!

Could you directly work on the **dev** branch? The file names and the structure have been a bit updated. 

What do you mean with a few says? If you have ideas of changes or new features it would of course be nice to add them, and if you contribute to the project you will be credited anyway!

For example I was hesitating about keeping the _Trimesh_ / _NumPy_ dependency (as we are working with memoryviews they may not be necessary) and thinking about implementing the tracking of face colors, which is already implemented in the _Simplify.h_ code, but other changes could be more relevant.

**Comment by bwoodsend** [comment]
> . I did not yet managed to create a setup file that would allow the module to be built installed at the same time

I'll have a look.

> What do you mean with a few says?

Oops that's a typo. It's meant to say *give me a few days*.

> For example I was hesitating about keeping the Trimesh / NumPy dependency (as we are working with memoryviews they may not be necessary) and thinking about implementing the tracking of face colors, which is already implemented in the Simplify.h code, but other changes could be more relevant.

I'd be quite keen to remove the dependency on Trimesh too since we only need vertices and faces (and possibly colors in the future) which are generic to any mesh library. I'd have to have a closer look at the source code to see how easy it would be to remove NumPy.

**Comment by Kramer84** [comment]
Finally I have the setup file now working, so its only matter of checking if there are no hidden bugs, writing some docs, (maybe removing the dependencies first) and then building wheels and putting it on pyPI!
edit: Maybe it's wiser to first just remove trimesh (as it doesn't induce any major changes in the code) and keep numpy for testing as long as tracking colors is not implemented.
edit2: if we remove trimesh as a dependency, do we for example use [numpy-stl](https://github.com/WoLpH/numpy-stl) to load the bunny example, or de we completely remove the stanford_bunny ?
edit3: pyPI package uploaded but not working :/ [https://pypi.org/project/pyfqmr/0.1/](https://pypi.org/project/pyfqmr/0.1/)

**Comment by bwoodsend** [comment]
>  edit3: pyPI package uploaded but not working :/ https://pypi.org/project/pyfqmr/0.1/

Ahh no. Wheels are a bit uglier than that. I'm surprised PyPI let you upload that egg. These days wheels need to be wheels (not eggs), we need a separate wheel for every permutation of OS + Python minor version so we'll end up with 20 of the things (fun fun), and the Linux ones need to be built in special docker containers so that their glibc versions are controlled (otherwise older Linux users will get ugly symbol version errors at runtime). But this is the bit I've done plenty of times so I'll tackle the wheels.

> edit2: if we remove trimesh as a dependency, do we for example use numpy-stl to load the bunny example, or de we completely remove the stanford_bunny ?

The quadric decimation algorithm requires the vertices in its `(vertices, faces)` input to be unique so, unless there's a hidden `uniquify_vertices()` function hiding in here which we can use, `numpy-stl` wouldn't work. But perhaps we could use `trimesh` only for tests and examples and highlight in those examples that any mesh library will do as long as you can get the raw vertices and faces (meshio springs to mind)?

**Comment by Kramer84** [comment]
> These days wheels need to be wheels (not eggs), we need a separate wheel for every permutation of OS + Python minor version so we'll end up with 20 of the things

Ouch, at least the project name is taken now, but it seems indeed a bit more tedious then previously thought! But no pyPI did not make any check, other than if the name had already been used.

And yeah, you're right, examples are examples, let's not bind dependencies to those. 

I will begin working on removing trimesh, and for removing numpy I assume the solution would be based on reusing the internal methods of the passed ndarray object, copying it, refilling it with the new values and truncating it a the right index.

**Comment by Kramer84** [comment]
@bwoodsend So now that the dependencies are removed, wheels built and some basic tests implemented, it should be the OK for merging the development branch with the master one, and updating the pyPI package? 

And do we keep the version at 1.0, retrograde it (as tracking face colors is not implemented) or does it matter at all with this sort of small project?

**Comment by bwoodsend** [comment]
> @bwoodsend So now that the dependencies are removed, wheels built and some basic tests implemented, it should be the OK for merging the development branch with the master one, and updating the pyPI package?

Yeah, #8 will mop up the wheels issue then we're good to go.

> And do we keep the version at 1.0, retrograde it (as tracking face colors is not implemented) or does it matter at all with this sort of small project?

I'd have set the initial version to 0.1.0 but irregardless, I think we should increment the minor version before releasing again.
