### ISSUE TITLE
Keeping track of the indices for upscaling

### ISSUE THREAD

**Issue by thangngoc89** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#38]
Hi there,

I’m using pyfqmr for mesh simplification before deep learning semantic segmentation. After I got the labels, is there anyway to “upscale” the label back to the original resolution? 

Thanks in advance

**Comment by bwoodsend** [comment]
The simplification process creates new vertices in between prior existing ones so if by *labels* you mean specific vertices on the simplified mesh, chances are that those labelled vertices don't exist on the original. Best I can suggest is that you use a [kdtree](http://pypi.org/project/pykdtree) to find the nearest original vertex.

**Comment by thangngoc89** [comment]
@bwoodsend thank you for your quick response. After looking into several python mesh simplification packages, I come to the conclusion that all packages doesn't keep indices between original and simplified indices so finding the nearest original vertex is needed (using kdtree like you suggested)
